
spring.datasource.url=jdbc:h2:tcp://localhost/./data/smartwarranty;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

llow-bean-definition-overriding=true


spring.main.web-application-type=none


logging.level.org.springframework=INFO

